ALTER TYPE "ExerciseType" ADD VALUE 'SHORT_ANSWER';
ALTER TYPE "ExerciseType" ADD VALUE 'TRANSFORMATION';
ALTER TYPE "ExerciseType" ADD VALUE 'DIALOGUE_REPLY';
ALTER TYPE "ExerciseType" ADD VALUE 'LISTENING_DICTATION';
ALTER TYPE "ExerciseType" ADD VALUE 'WRITING_PROMPT';
